@startuml

class NdArray<T> {
  - m_shape : vector<size_t>
  - m_stride_size : vector<size_t>
  - m_container : ContainerWrapper<T>
  --
  + NdArray(shape)
  + NdArray(shape, data)
  + shape() const : vector<size_t>
  + reshape()
  + at(coords) : T
  + begin() : iterator
  + end() : iterator
  + data() : Container<T>
  + size() : size_t
  -- operators --
  + operator = ()
  + operator == () : bool
  + operator != () : bool
}

class ContainerWrapper<T> {
  + m_data : T*
  --
  + size() : size_t
  + copy() : ContainerWrapper<T>
}

NdArray o-- ContainerWrapper

@enduml
